version: '3'
services:
  mysql-db:
    image: mysql
    container_name: mysqldbhost
    restart: always
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: password
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    image:
      amcef/docker:1
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db